title: "黄芳薪 🌷"

description: "黄芳薪｜南京大学新闻传播学院博士研究生｜健康传播与无障碍传播"

url: "https://huangfangxin0517.github.io"

author:
  name: "黄芳薪"
  email: "fangxinhuang@smail.nju.edu.cn"

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
